
on:
  push

# on:
#   schedule:
#     - cron:  '55 5 * * *'

name: Build macOS installer daily

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build
      run: |
        ./build.sh

    - name: Logs
      run: |
        echo "::group::config.log"
        cat _build/R4/high-sierra-x86_64/R-devel/config.log || true
        echo "::endgroup::"
        echo "::group::Build log"
        cat _build/R4/high-sierra-x86_64/R-devel.build || true
        echo "::endgroup::"

    - name: Upload build tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: R-devel.pkg
        path: _build/R4/deploy/high-sierra/R-devel/x86_64/R-devel.tar.gz
        if-no-files-found: error

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: R-devel.pkg
        path: _build/R4/deploy/high-sierra/R-devel/R-devel.pkg
        if-no-files-found: error
