
on:
  schedule:
    - cron:  '55 5 * * *'
  workflow_dispatch:

name: Build macOS installer daily

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Cleanup MacOS system
      if: runner.os == 'macos'
      run: |
        brew uninstall --force --ignore-dependencies $(brew list) 2>&1 | sed 's/Warning/Note/g'
        curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        bash uninstall.sh --force --quiet 2>&1 | sed 's/Warning/Note/g'
        hash -r && rm uninstall.sh

    - name: Select Xcode
      run: |
        sudo xcode-select -s "/Applications/Xcode_11.7.app"
        sudo rm /Applications/Xcode.app
        sudo ln -s /Applications/Xcode_11.7.app /Applications/Xcode.app

    - name: Build
      run: |
        ./build.sh

    - name: Logs
      if: ${{ always() }}
      run: |
        echo "::group::nightly.log"
        cat _build/R4/nightly.log
        echo "::endgroup::"
        echo "::group::config.log"
        cat _build/R4/high-sierra-x86_64/R-devel/config.log || true
        echo "::endgroup::"
        echo "::group::Build log"
        cat _build/R4/high-sierra-x86_64/R-devel.build || true
        echo "::endgroup::"

    - name: Upload R-next
      if: false
      uses: actions/upload-artifact@v3
      with:
        name: R-next.pkg
        path: |
          _build/R4/deploy/high-sierra/R-4-2-branch/x86_64/R-*.tar.gz
          _build/R4/deploy/high-sierra/R-4-2-branch/R-devel.pkg
        if-no-files-found: error

    - name: Upload R-devel
      uses: actions/upload-artifact@v3
      with:
        name: R-devel.pkg
        path: |
          _build/R4/deploy/high-sierra/R-devel/x86_64/R-*.tar.gz
          _build/R4/deploy/high-sierra/R-devel/R-devel.pkg
        if-no-files-found: error
